In [1]:
import pandas as pd

df = pd.read_csv('alldata.csv')
df.columns

Index(['Unnamed: 0', '성별', '연령대', '거주지', '가구소득정도', '사용목적1순위값', '사용목적2순위값',
       '평일일평균레저시간값', '주말일평균레저시간값', '휴식오락사용비율', '취미사용비율', '본인계발사용비율',
       '대인관계교제사용비율', '기타사용비율', '관심레저활동1순위값'],
      dtype='object')

In [2]:
df = df.drop(['Unnamed: 0',
            #  '사용목적1순위값',
            #  '사용목적2순위값',
            #  '평일일평균레저시간값',
            #  '주말일평균레저시간값',
            #  '휴식오락사용비율',
            #  '취미사용비율',
            #  '본인계발사용비율',
            #  '대인관계교제사용비율',
            #  '기타사용비율',
             ],
             axis=1)
df.head()

,성별,연령대,거주지,가구소득정도,사용목적1순위값,사용목적2순위값,평일일평균레저시간값,주말일평균레저시간값,휴식오락사용비율,취미사용비율,본인계발사용비율,대인관계교제사용비율,기타사용비율,관심레저활동1순위값
0,M,30대,서울특별시,300이상500만원 미만,스트레스 해소를 위해,가족-지인 등과 시간을 보내기 위해,2,3,30.0,40.0,20.0,10.0,0.0,골프 직접 하기
1,F,40대,서울특별시,700만원 이상,대인 관계-교제를 위해,마음의 안정-휴식을 위해,1,3,0.0,0.0,50.0,50.0,0.0,영상 컨텐츠 시청
2,F,50대,서울특별시,500이상700만원 미만,가족-지인 등과 시간을 보내기 위해,대인 관계-교제를 위해,10,12,80.0,0.0,0.0,20.0,0.0,쇼핑
3,M,40대,서울특별시,700만원 이상,가족-지인 등과 시간을 보내기 위해,마음의 안정-휴식을 위해,1,5,40.0,20.0,20.0,20.0,0.0,보드게임-퍼즐-바둑-장기-체스 등
4,F,60대,제주특별자치도,700만원 이상,대인 관계-교제를 위해,남는 시간을 보내기 위해,10,10,70.0,10.0,10.0,5.0,5.0,쇼핑

In [3]:
# 항목합치기

friend = ['SNS -인터넷 커뮤니티 활동',
        '가족-친지 만남',
        '계모임-동창회-사교모임',
        '기타 사회교류',
        '친구-이성친구 만남',
        '수다-잡담하기',
        '종교활동',
        '수다-잡담하기',
        '음주-유흥',
        ]
df = df.replace(friend, '사교활동')


game= '''갬블
게임
보드게임-퍼즐-바둑-장기-체스 등
e스포츠 영상 시청
e스포츠 현장 관람'''
games = game.split("\n")
df = df.replace(games, "게임")


sport = '''걷기-속보-조깅 직접 하기
구기스포츠 직접 하기
기타 스포츠-운동 직접하기
등산 직접 하기
라켓스포츠 직접 하기
무도-격투기 직접 하기
수상레저스포츠 직접 하기
수영 직접 하기
줄넘기-맨손체조-스트레칭 직접 하기
볼링_ 당구-포켓볼 직접 하기
요가-필라테스 직접 하기
익스트림스포츠 직접하기
자전거-싸이클-산악자전거 직접 타기
헬스-보디빌딩 직접 하기
겨울레저스포츠 직접 하기
골프 직접 하기
댄스스포츠 직접 하기
낚시'''
sports = sport.split("\n")
df = df.replace(sports, "운동")


sports_watching = '''격투 스포츠 영상 시청
격투 스포츠 현장 관람
국내 프로스포츠 영상 시청
국내 프로스포츠 현장 관람
기타 스포츠 영상-현장 관람
골프 현장 관람
골프 영상 시청
해외 프로스포츠 영상 시청'''
sports_watchings = sports_watching.split("\n")
df = df.replace(sports_watchings, "스포츠 관람")


trip = '''해외여행
국내 여행
기타 관광-여행
캠핑-차박
소풍-피크닉
맛집-카페 탐방
테마파크-시설 방문'''
trips = trip.split("\n")
df = df.replace(trips, "여행")


culture = '''기타 문화예술관람
무용 공연 관람
문학 행사 관람
미술관-전시관 관람
음악 공연 관람
박물관 관람
연극-뮤지컬 관람
영화관 관람'''
cultures = culture.split('\n')
df = df.replace(cultures, "문화 예술 관람")

reading = '''독서
만화책 보기
신문-잡지보기'''
reading_books = reading.split('\n')
df = df.replace(reading_books, "독서")

tired = '''기타 취미-오락-휴식
낮잠자기
산책-걷기
온천-사우나-찜질방
드라이브
반려동물 돌보기'''
tired_ = tired.split('\n')
df = df.replace(tired_, "휴식")

doing_culture = '''기타 문화예술 직접 활동 및 수강하기
춤-무용 직접 활동 및 수강하기
문학 직접 활동 및 수강하기
미술 직접 활동 및 수강하기
전통예술 직접 활동 및 수강하기
음악 직접 활동 및 수강하기
영상 컨텐츠 제작
사진 직접 활동 및 수강하기
생활공예-원예
인테리어'''
doing_cultures = doing_culture.split('\n')
df = df.replace(doing_cultures, "문화 예술 활동")


self = '''기타 자기계발-자기관리
어학-기술-자격증 취득
미용'''
selfs = self.split('\n')
df = df.replace(selfs, "자기계발")


exprience = '''축제 참가
액티비티-체험'''
expriences = exprience.split('\n')
df = df.replace(expriences, "체험 활동")

In [4]:
len(df['관심레저활동1순위값'].unique())

18

In [5]:
# 레이블 인코딩

from sklearn.preprocessing import LabelEncoder
labelcol = ['성별', '연령대' , '가구소득정도', 
            '거주지', 
            '사용목적1순위값', '사용목적2순위값', 
            '관심레저활동1순위값']
le = LabelEncoder()
for column in labelcol:
    df[column] = le.fit_transform(df[column])

print(df)
original_labels = le.classes_
encoded_labels = le.transform(le.classes_)
mapping = dict(zip(original_labels, encoded_labels))
print("\n성별 매핑:", mapping)

       성별  연령대  거주지  가구소득정도  사용목적1순위값  사용목적2순위값  평일일평균레저시간값  주말일평균레저시간값  \
0       1    1    8       1         6         0           2           3
1       0    2    8       3         4         5           1           3
2       0    3    8       2         0         4          10          12
3       1    2    8       3         0         5           1           5
4       0    4   14       3         4         3          10          10
...    ..  ...  ...     ...       ...       ...         ...         ...
31585   1    1   12       1         8         6           1           3
31586   0    2    6       2         5         0           1           2
31587   0    0    0       4         5         9          16           8
31588   0    4    7       0         7         9           6           8
31589   0    0    4       4         8         6          15          15

       휴식오락사용비율  취미사용비율  본인계발사용비율  대인관계교제사용비율  기타사용비율  관심레저활동1순위값
0          30.0    40.0      20.0        10.0     0.0          13
1           0.0     0.0      50.0        50.0     0.0          11
2          80.0     0.0       0.0        20.0     0.0           7
3          40.0    20.0      20.0        20.0     0.0           0
4          70.0    10.0      10.0         5.0     5.0           7
...         ...     ...       ...         ...     ...         ...
31585      50.0    30.0      20.0         0.0     0.0           4
31586      80.0     5.0      10.0         5.0     0.0          11
31587      20.0    10.0       0.0        70.0     0.0           2
31588      30.0    20.0      30.0        20.0     0.0          10
31589      90.0     0.0       5.0         5.0     0.0           4

[31590 rows x 14 columns]

성별 매핑: {'게임': 0, '독서': 1, '문화 예술 관람': 2, '문화 예술 활동': 3, '사교활동': 4, '사진 촬영': 5, '사회봉사활동': 6, '쇼핑': 7, '수집': 8, '스포츠 관람': 9, '여행': 10, '영상 컨텐츠 시청': 11, '요리-베이킹': 12, '운동': 13, '음악-라디오 감상': 14, '자기계발': 15, '체험 활동': 16, '휴식': 17}

In [6]:
for i in mapping:
    print(i)

게임
독서
문화 예술 관람
문화 예술 활동
사교활동
사진 촬영
사회봉사활동
쇼핑
수집
스포츠 관람
여행
영상 컨텐츠 시청
요리-베이킹
운동
음악-라디오 감상
자기계발
체험 활동
휴식

In [7]:
# array 위도 경도 거주지대신 넣기

In [40]:
df.head()

,성별,연령대,거주지,가구소득정도,사용목적1순위값,사용목적2순위값,평일일평균레저시간값,주말일평균레저시간값,휴식오락사용비율,취미사용비율,본인계발사용비율,대인관계교제사용비율,기타사용비율,관심레저활동1순위값
0,1,1,8,1,6,0,2,3,30.0,40.0,20.0,10.0,0.0,13
1,0,2,8,3,4,5,1,3,0.0,0.0,50.0,50.0,0.0,11
2,0,3,8,2,0,4,10,12,80.0,0.0,0.0,20.0,0.0,7
3,1,2,8,3,0,5,1,5,40.0,20.0,20.0,20.0,0.0,0
4,0,4,14,3,4,3,10,10,70.0,10.0,10.0,5.0,5.0,7

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31590 entries, 0 to 31589
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   성별          31590 non-null  int32
 1   연령대         31590 non-null  int32
 2   거주지         31590 non-null  int32
 3   가구소득정도      31590 non-null  int32
 4   사용목적1순위값    31590 non-null  int32
 5   사용목적2순위값    31590 non-null  int32
 6   평일일평균레저시간값  31590 non-null  int64
 7   주말일평균레저시간값  31590 non-null  int64
 8   휴식오락사용비율    31590 non-null  float64
 9   취미사용비율      31590 non-null  float64
 10  본인계발사용비율    31590 non-null  float64
 11  대인관계교제사용비율  31590 non-null  float64
 12  기타사용비율      31590 non-null  float64
 13  관심레저활동1순위값  31590 non-null  int32
dtypes: float64(5), int32(7), int64(2)
memory usage: 2.5 MB

In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.impute import SimpleImputer

In [ ]:
# import pandas as pd
# import numpy as np
# from sklearn.model_selection import train_test_split, GridSearchCV
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import accuracy_score
# from tqdm import tqdm
# from sklearn.model_selection import KFold

# # 데이터 준비 (이 부분은 실제 데이터로 대체하세요)
# # df = pd.DataFrame(...)  # 여기에 실제 데이터를 로드하세요

# X = df.drop('관심레저활동1순위값', axis=1)
# y = df['관심레저활동1순위값']
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

# # tqdm을 적용한 사용자 정의 CV splitter
# class TqdmKFold(KFold):
#     def __init__(self, n_splits=5, shuffle=True, random_state=None):
#         super().__init__(n_splits=n_splits, shuffle=shuffle, random_state=random_state)
    
#     def split(self, X, y=None, groups=None):
#         return tqdm(super().split(X, y, groups), total=self.n_splits, desc="CV Folds")


# # 탐색할 하이퍼파라미터 범위 정의
# param_grid = {
#     'n_estimators': [100, 200, 300],
#     'max_depth': [None, 10, 20, 30],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4],
#     'max_features': ['auto', 'sqrt']
# }

# # 그리드 탐색 객체 생성
# grid_search = GridSearchCV(RandomForestClassifier(random_state=42), 
#                            param_grid, 
#                            cv=TqdmKFold(n_splits=5, shuffle=True, random_state=42), 
#                            n_jobs=-1, 
#                            verbose=0)  # verbose를 0으로 설정하여 GridSearchCV의 기본 출력을 억제

# # 그리드 탐색 수행
# with tqdm(total=len(param_grid['n_estimators']) * len(param_grid['max_depth']) * 
#           len(param_grid['min_samples_split']) * len(param_grid['min_samples_leaf']) * 
#           len(param_grid['max_features']), desc="Parameter Combinations") as pbar:
#     def update(*args, **kwargs):
#         pbar.update(1)
#     grid_search.fit(X_train, y_train, callback=update)

# # 최적의 파라미터와 점수 출력
# print("Best parameters:", grid_search.best_params_)
# print("Best cross-validation score:", grid_search.best_score_)

# # 테스트 세트로 평가
# y_pred = grid_search.predict(X_test)
# accuracy = accuracy_score(y_test, y_pred)
# print(f"Test set accuracy: {accuracy:.4f}")

In [9]:
X = df.drop('관심레저활동1순위값', axis=1)
y = df['관심레저활동1순위값']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [43]:
from sklearn.model_selection import GridSearchCV

# 탐색할 하이퍼파라미터 범위 정의
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt']
}

# 그리드 탐색 객체 생성
grid_search = GridSearchCV(RandomForestClassifier(random_state=42), 
                           param_grid, 
                           cv=5, 
                           n_jobs=-1, 
                           verbose=2)

# 그리드 탐색 수행
grid_search.fit(X_train, y_train)


# model = RandomForestClassifier(n_estimators=100, random_state=42)
# model.fit(X_train, y_train)
y_pred = grid_search.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"정확도: {accuracy:.2f}")

Fitting 5 folds for each of 216 candidates, totalling 1080 fits

c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning:
540 fits failed out of a total of 1080.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
309 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
231 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\Admin\miniconda3\envs\gumi_env310\lib\site-packages\sklearn\model_selection\_search.py:1051: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.25755776 0.25902202 0.26005072
 0.26836034 0.27239644 0.27239628 0.27777783 0.27920238 0.27829231
 0.27164473 0.27188228 0.27299019 0.27291077 0.27469151 0.27469146
 0.27758005 0.27849009 0.27845055 0.27872744 0.28007292 0.27920231
 0.27872744 0.28007292 0.27920231 0.2767489  0.27837126 0.27936077
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.28628545 0.28767014 0.28731404
 0.28640413 0.28561258 0.28676027 0.28549375 0.28565211 0.28565213
 0.28585005 0.28588949 0.28525648 0.28486074 0.28588963 0.28660188
 0.28517723 0.28478156 0.28608731 0.28624567 0.28632482 0.28691847
 0.28624567 0.28632482 0.28691847 0.28565217 0.28557298 0.28569169
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.25807235 0.26198961 0.26282077
 0.27148635 0.27279214 0.27263398 0.27746131 0.27868806 0.27833195
 0.26946825 0.27267362 0.27204046 0.27310874 0.27354405 0.27465196
 0.27785704 0.27872757 0.27951894 0.27904414 0.27955844 0.27967726
 0.27904414 0.27955844 0.27967726 0.27991465 0.28090401 0.28141825
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.25530234 0.25728079 0.26001118
 0.26804388 0.27318784 0.27298985 0.2778174  0.27924195 0.2783319
 0.27200087 0.2723967  0.27338585 0.27322734 0.27477067 0.27484973
 0.27718432 0.27868795 0.2783714  0.27872744 0.28007292 0.27920231
 0.27872744 0.28007292 0.27920231 0.2767489  0.27837126 0.27936077]
  warnings.warn(

정확도: 0.28

In [10]:
X_train

,성별,연령대,거주지,가구소득정도,사용목적1순위값,사용목적2순위값,평일일평균레저시간값,주말일평균레저시간값,휴식오락사용비율,취미사용비율,본인계발사용비율,대인관계교제사용비율,기타사용비율
25669,0,4,8,3,5,3,6,6,80.0,20.0,0.0,0.0,0.0
27489,0,1,4,2,0,5,5,12,90.0,0.0,0.0,10.0,0.0
4090,1,4,8,0,5,4,5,10,40.0,30.0,0.0,30.0,0.0
17389,1,0,8,3,6,9,2,5,30.0,30.0,10.0,30.0,0.0
19485,0,0,16,0,7,0,1,5,50.0,0.0,20.0,30.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023,1,1,8,1,0,6,4,10,70.0,20.0,0.0,10.0,0.0
7259,1,0,8,1,6,5,1,6,0.0,10.0,70.0,20.0,0.0
21584,0,0,5,4,5,8,2,2,10.0,0.0,10.0,80.0,0.0
3775,1,4,1,1,8,7,4,5,20.0,0.0,0.0,0.0,80.0
10137,1,1,8,1,8,1,2,7,50.0,0.0,0.0,0.0,50.0

In [11]:
rf = RandomForestClassifier(random_state=11)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.25783475783475784

In [12]:
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state=11)
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.2668566001899335